apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: my-app
    image: my-app:latest
    resources:
      ### res
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

# nodeSelector: Ensures that the pod runs only on nodes labeled with disktype=ssd.
# Node Labels: Nodes must have the appropriate label, which can be set using:
# kubectl label nodes <node-name> disktype=ssd
