apiVersion: v1
kind: Pod 
metadata:
  name: myapp
  labels:
    name: myapp-pod 
spec: 
  containers:
    - name: myapp-container
      image: busybox:1.28
      env:
        - name: FIRSTNAME
          value:  "phantomsoldierking"
