# running declatrive k8s resources
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
  labels:
    env:  demo 
    type: frontend
spec:
  containers:
    - name: nginx-container 
      image: nginx
      ports:
        - containerPort: 80
