apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

# scaleTargetRef – Specifies the target deployment (webapp) to scale.
# minReplicas & maxReplicas – Define the range of pod replicas.
# metrics – Uses CPU utilization as the scaling metric with a target of 50% usage.

# To apply the HPA configuration: kubectl apply -f hpa.yaml

# To check the status of the HPA: kubectl get hpa

# To delete an HPA: kubectl delete hpa webapp-hpa
