apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USERNAME: cG93ZXI= # 'power' in base64 encoding
  DB_PASSWORD: c2VjdXJlX2p3b3A= # 'secure_jwop' in base64 encoding

# Secure Storage: Stores sensitive data in an encrypted format within the Kubernetes cluster.
# Access Control: Can be restricted with RBAC (Role-Based Access Control) to limit access to authorized users and services.
# Multiple Usage: Can be injected as environment variables, volumes, or as part of a service account for pod authentication.
# Base64 Encoding: While secrets are base64-encoded, it’s important to note that base64 is not encryption, so you should consider using encryption at rest for enhanced security.
